### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by JourdanDixon** [thomashaertel/MultiSpinner#3]
Hi there, I'm having some trouble adding this into my Android Studio app.  When I add into my compile dependencies it returns an error upon gradle sync.  I tried following the install instructions included, but no go.  Can you help?

Error:(26, 13) Failed to resolve: com.thomashaertel:multispinner:0.1.0
<a href="openFile">Show in File</a><br>
<a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by thomashaertel** [comment]
Hi, please update your build file to version multispinner:0.1.1:

compile 'com.thomashaertel:multispinner:0.1.1@aar'

This should work.

Best regards
Thomas

**Comment by NikhilAndroidDev** [comment]
Still not working .

**Comment by fouadkada** [comment]
this works for me
`compile group: 'com.thomashaertel', name: 'multispinner', version: '0.1.1'`

**Comment by parmarhardik58** [comment]
> compile group: 'com.thomashaertel', name: 'multispinner', version: '0.1.1'

Working for me,
